grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: ExtraTreesRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 100
    search_param_grid:
      max_depth:
      - 4
      bootstrap:
      - True 
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 40
      min_samples_leaf: 2
    search_param_grid:
      min_samples_leaf:
      - 2
      - 4
      - 6
      n_estimators:
      - 50
      - 100 
      - 80